name: sa_app_registro_ponto
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  firebase_core: ^3.1.1
  cloud_firestore: ^5.4.4
  intl: ^0.19.0
  flutter:
    sdk: flutter
  geolocator: ^14.0.2
  http: ^1.5.0
  local_auth: ^2.1.6 
  shared_preferences: ^2.2.2
  firebase_auth: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
